
package com.oracle.xmlns.ust.tools.bot.integrator.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebService(name = "IntegratorService", targetNamespace = "http://xmlns.oracle.com/ust/tools/bot/integrator/service/")
@XmlSeeAlso({ com.oracle.xmlns.adf.svc.errors.ObjectFactory.class,
              com.oracle.xmlns.ust.tools.bot.integrator.service.types.ObjectFactory.class,
              sdo.commonj.ObjectFactory.class, sdo.commonj.java.ObjectFactory.class
    })
public interface IntegratorService {


    /**
     *
     * @param message
     * @return
     *     returns java.lang.String
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/ust/tools/bot/integrator/service/process")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/ust/tools/bot/integrator/service/types/")
    @RequestWrapper(localName = "process",
                    targetNamespace = "http://xmlns.oracle.com/ust/tools/bot/integrator/service/types/",
                    className = "com.oracle.xmlns.ust.tools.bot.integrator.service.types.Process")
    @ResponseWrapper(localName = "processResponse",
                     targetNamespace = "http://xmlns.oracle.com/ust/tools/bot/integrator/service/types/",
                     className = "com.oracle.xmlns.ust.tools.bot.integrator.service.types.ProcessResponse")
    public String process(@WebParam(name = "message",
                                    targetNamespace = "http://xmlns.oracle.com/ust/tools/bot/integrator/service/types/")
                          String message) throws ServiceException;

}
