<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="IntegratorService" targetNamespace="http://xmlns.oracle.com/ust/tools/bot/integrator/service/" xmlns:errors="http://xmlns.oracle.com/adf/svc/errors/" xmlns:tns="http://xmlns.oracle.com/ust/tools/bot/integrator/service/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:types="http://xmlns.oracle.com/ust/tools/bot/integrator/service/types/">
  <wsp:Policy xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" wsu:Id="wsaddr_policy" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy">
    <wsaw:UsingAddressing xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl"/>
  </wsp:Policy>
  <wsp:Policy xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" wsu:Id="wss_saml_bearer_or_username_token_service_policy" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SupportingTokens xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <wsp:Policy>
            <sp:SamlToken sp:IncludeToken="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy/IncludeToken/AlwaysToRecipient">
              <wsp:Policy>
                <sp:WssSamlV11Token11/>
              </wsp:Policy>
            </sp:SamlToken>
          </wsp:Policy>
        </sp:SupportingTokens>
      </wsp:All>
      <wsp:All>
        <sp:SupportingTokens xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <wsp:Policy>
            <sp:UsernameToken sp:IncludeToken="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy/IncludeToken/AlwaysToRecipient">
              <wsp:Policy>
                <sp:WssUsernameToken10/>
              </wsp:Policy>
            </sp:UsernameToken>
          </wsp:Policy>
        </sp:SupportingTokens>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" wsu:Id="wss_saml_token_bearer_client_policy" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <sp:SupportingTokens xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
      <wsp:Policy>
        <sp:SamlToken sp:IncludeToken="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy/IncludeToken/AlwaysToRecipient">
          <wsp:Policy>
            <sp:WssSamlV11Token11/>
          </wsp:Policy>
        </sp:SamlToken>
      </wsp:Policy>
    </sp:SupportingTokens>
  </wsp:Policy>
  <wsdl:import namespace="http://xmlns.oracle.com/adf/svc/errors/" location="ServiceException.wsdl"/>
  <wsdl:types>
    <schema xmlns="http://www.w3.org/2001/XMLSchema">
      <import namespace="http://xmlns.oracle.com/ust/tools/bot/integrator/service/types/" schemaLocation="IntegratorService.xsd"/>
    </schema>
  </wsdl:types>
  <wsdl:message name="IntegratorService_process">
    <wsdl:part name="parameters" element="types:process"/>
  </wsdl:message>
  <wsdl:message name="IntegratorService_processResponse">
    <wsdl:part name="parameters" element="types:processResponse"/>
  </wsdl:message>
  <wsdl:portType name="IntegratorService">
    <wsdl:documentation/>
    <wsdl:operation name="process">
      <wsdl:input message="tns:IntegratorService_process"/>
      <wsdl:output message="tns:IntegratorService_processResponse"/>
      <wsdl:fault name="ServiceException" message="errors:ServiceException"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="IntegratorServiceSoapHttp" type="tns:IntegratorService">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#wss_saml_bearer_or_username_token_service_policy" wsdl:required="false"/>
    <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#wsaddr_policy" wsdl:required="false"/>
    <wsdl:operation name="process">
      <soap:operation soapAction="http://xmlns.oracle.com/ust/tools/bot/integrator/service/process"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="ServiceException">
        <soap:fault name="ServiceException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="IntegratorService">
    <wsdl:port name="IntegratorServiceSoapHttpPort" binding="tns:IntegratorServiceSoapHttp">
      <soap:address location="http://slc06ukb.us.oracle.com:7011/Integrator/IntegratorService"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>