package ust.tools.bot.integrator.model.view;

import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 06 16:55:17 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class IntgEnvironmentsVORowImpl extends ViewRowImpl {

    public static final int ENTITY_INTGENVIRONMENTS = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        EnvironmentId,
        EnvironmentName,
        EnvironmentType,
        AdeBranch,
        WindowHours,
        BuildFlag;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return ust.tools
                      .bot
                      .integrator
                      .model
                      .view
                      .IntgEnvironmentsVORowImpl
                      .AttributesEnum
                      .firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return ust.tools
                      .bot
                      .integrator
                      .model
                      .view
                      .IntgEnvironmentsVORowImpl
                      .AttributesEnum
                      .firstIndex() + ust.tools
                                         .bot
                                         .integrator
                                         .model
                                         .view
                                         .IntgEnvironmentsVORowImpl
                                         .AttributesEnum
                                         .staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = ust.tools
                          .bot
                          .integrator
                          .model
                          .view
                          .IntgEnvironmentsVORowImpl
                          .AttributesEnum
                          .values();
            }
            return vals;
        }
    }

    public static final int ENVIRONMENTID = AttributesEnum.EnvironmentId.index();
    public static final int ENVIRONMENTNAME = AttributesEnum.EnvironmentName.index();
    public static final int ENVIRONMENTTYPE = AttributesEnum.EnvironmentType.index();
    public static final int ADEBRANCH = AttributesEnum.AdeBranch.index();
    public static final int WINDOWHOURS = AttributesEnum.WindowHours.index();
    public static final int BUILDFLAG = AttributesEnum.BuildFlag.index();

    /**
     * This is the default constructor (do not remove).
     */
    public IntgEnvironmentsVORowImpl() {
    }

    /**
     * Gets IntgEnvironments entity object.
     * @return the IntgEnvironments
     */
    public EntityImpl getIntgEnvironments() {
        return (EntityImpl) getEntity(ENTITY_INTGENVIRONMENTS);
    }

    /**
     * Gets the attribute value for ENVIRONMENT_ID using the alias name EnvironmentId.
     * @return the ENVIRONMENT_ID
     */
    public Long getEnvironmentId() {
        return (Long) getAttributeInternal(ENVIRONMENTID);
    }

    /**
     * Sets <code>value</code> as attribute value for ENVIRONMENT_ID using the alias name EnvironmentId.
     * @param value value to set the ENVIRONMENT_ID
     */
    public void setEnvironmentId(Long value) {
        setAttributeInternal(ENVIRONMENTID, value);
    }

    /**
     * Gets the attribute value for ENVIRONMENT_NAME using the alias name EnvironmentName.
     * @return the ENVIRONMENT_NAME
     */
    public String getEnvironmentName() {
        return (String) getAttributeInternal(ENVIRONMENTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for ENVIRONMENT_NAME using the alias name EnvironmentName.
     * @param value value to set the ENVIRONMENT_NAME
     */
    public void setEnvironmentName(String value) {
        setAttributeInternal(ENVIRONMENTNAME, value);
    }

    /**
     * Gets the attribute value for ENVIRONMENT_TYPE using the alias name EnvironmentType.
     * @return the ENVIRONMENT_TYPE
     */
    public String getEnvironmentType() {
        return (String) getAttributeInternal(ENVIRONMENTTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for ENVIRONMENT_TYPE using the alias name EnvironmentType.
     * @param value value to set the ENVIRONMENT_TYPE
     */
    public void setEnvironmentType(String value) {
        setAttributeInternal(ENVIRONMENTTYPE, value);
    }

    /**
     * Gets the attribute value for ADE_BRANCH using the alias name AdeBranch.
     * @return the ADE_BRANCH
     */
    public String getAdeBranch() {
        return (String) getAttributeInternal(ADEBRANCH);
    }

    /**
     * Sets <code>value</code> as attribute value for ADE_BRANCH using the alias name AdeBranch.
     * @param value value to set the ADE_BRANCH
     */
    public void setAdeBranch(String value) {
        setAttributeInternal(ADEBRANCH, value);
    }

    /**
     * Gets the attribute value for WINDOW_HOURS using the alias name WindowHours.
     * @return the WINDOW_HOURS
     */
    public String getWindowHours() {
        return (String) getAttributeInternal(WINDOWHOURS);
    }

    /**
     * Sets <code>value</code> as attribute value for WINDOW_HOURS using the alias name WindowHours.
     * @param value value to set the WINDOW_HOURS
     */
    public void setWindowHours(String value) {
        setAttributeInternal(WINDOWHOURS, value);
    }

    /**
     * Gets the attribute value for BUILD_FLAG using the alias name BuildFlag.
     * @return the BUILD_FLAG
     */
    public String getBuildFlag() {
        return (String) getAttributeInternal(BUILDFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for BUILD_FLAG using the alias name BuildFlag.
     * @param value value to set the BUILD_FLAG
     */
    public void setBuildFlag(String value) {
        setAttributeInternal(BUILDFLAG, value);
    }
}

