package ust.tools.bot.integrator.model.view;

import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 06 16:56:39 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class IntgProductsVORowImpl extends ViewRowImpl {

    public static final int ENTITY_INTGPRODUCTS = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        ProductId,
        ProductCode,
        BuildFile,
        EnvironmentIds,
        IntegratorEmailIds;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return IntgProductsVORowImpl.AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return IntgProductsVORowImpl.AttributesEnum.firstIndex() + IntgProductsVORowImpl.AttributesEnum
                                                                                            .staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = IntgProductsVORowImpl.AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int PRODUCTID = AttributesEnum.ProductId.index();
    public static final int PRODUCTCODE = AttributesEnum.ProductCode.index();
    public static final int BUILDFILE = AttributesEnum.BuildFile.index();
    public static final int ENVIRONMENTIDS = AttributesEnum.EnvironmentIds.index();
    public static final int INTEGRATOREMAILIDS = AttributesEnum.IntegratorEmailIds.index();

    /**
     * This is the default constructor (do not remove).
     */
    public IntgProductsVORowImpl() {
    }

    /**
     * Gets IntgProducts entity object.
     * @return the IntgProducts
     */
    public EntityImpl getIntgProducts() {
        return (EntityImpl) getEntity(ENTITY_INTGPRODUCTS);
    }

    /**
     * Gets the attribute value for PRODUCT_ID using the alias name ProductId.
     * @return the PRODUCT_ID
     */
    public Long getProductId() {
        return (Long) getAttributeInternal(PRODUCTID);
    }

    /**
     * Sets <code>value</code> as attribute value for PRODUCT_ID using the alias name ProductId.
     * @param value value to set the PRODUCT_ID
     */
    public void setProductId(Long value) {
        setAttributeInternal(PRODUCTID, value);
    }

    /**
     * Gets the attribute value for PRODUCT_CODE using the alias name ProductCode.
     * @return the PRODUCT_CODE
     */
    public String getProductCode() {
        return (String) getAttributeInternal(PRODUCTCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for PRODUCT_CODE using the alias name ProductCode.
     * @param value value to set the PRODUCT_CODE
     */
    public void setProductCode(String value) {
        setAttributeInternal(PRODUCTCODE, value);
    }

    /**
     * Gets the attribute value for BUILD_FILE using the alias name BuildFile.
     * @return the BUILD_FILE
     */
    public String getBuildFile() {
        return (String) getAttributeInternal(BUILDFILE);
    }

    /**
     * Sets <code>value</code> as attribute value for BUILD_FILE using the alias name BuildFile.
     * @param value value to set the BUILD_FILE
     */
    public void setBuildFile(String value) {
        setAttributeInternal(BUILDFILE, value);
    }

    /**
     * Gets the attribute value for ENVIRONMENT_IDS using the alias name EnvironmentIds.
     * @return the ENVIRONMENT_IDS
     */
    public String getEnvironmentIds() {
        return (String) getAttributeInternal(ENVIRONMENTIDS);
    }

    /**
     * Sets <code>value</code> as attribute value for ENVIRONMENT_IDS using the alias name EnvironmentIds.
     * @param value value to set the ENVIRONMENT_IDS
     */
    public void setEnvironmentIds(String value) {
        setAttributeInternal(ENVIRONMENTIDS, value);
    }

    /**
     * Gets the attribute value for INTEGRATOR_EMAIL_IDS using the alias name IntegratorEmailIds.
     * @return the INTEGRATOR_EMAIL_IDS
     */
    public String getIntegratorEmailIds() {
        return (String) getAttributeInternal(INTEGRATOREMAILIDS);
    }

    /**
     * Sets <code>value</code> as attribute value for INTEGRATOR_EMAIL_IDS using the alias name IntegratorEmailIds.
     * @param value value to set the INTEGRATOR_EMAIL_IDS
     */
    public void setIntegratorEmailIds(String value) {
        setAttributeInternal(INTEGRATOREMAILIDS, value);
    }
}

