package ust.tools.bot.integrator.model.view;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 06 16:56:39 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class IntgProductsVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public IntgProductsVOImpl() {
    }

    /**
     * Returns the variable value for bindProductCode.
     * @return variable value for bindProductCode
     */
    public String getbindProductCode() {
        return (String) ensureVariableManager().getVariableValue("bindProductCode");
    }

    /**
     * Sets <code>value</code> for variable bindProductCode.
     * @param value value to bind as bindProductCode
     */
    public void setbindProductCode(String value) {
        ensureVariableManager().setVariableValue("bindProductCode", value);
    }
}

