package ust.tools.bot.integrator.model.view;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 06 16:55:18 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class IntgEnvironmentsVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public IntgEnvironmentsVOImpl() {
    }

    /**
     * Returns the variable value for bingEnvironmentId.
     * @return variable value for bingEnvironmentId
     */
    public Long getbingEnvironmentId() {
        return (Long) ensureVariableManager().getVariableValue("bingEnvironmentId");
    }

    /**
     * Sets <code>value</code> for variable bingEnvironmentId.
     * @param value value to bind as bingEnvironmentId
     */
    public void setbingEnvironmentId(Long value) {
        ensureVariableManager().setVariableValue("bingEnvironmentId", value);
    }
}

