package ust.tools.bot.integrator.model.view;

import java.sql.Timestamp;

import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 06 16:54:56 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class IntgDeploymentRequestsVORowImpl extends ViewRowImpl {


    public static final int ENTITY_INTGDEPLOYMENTREQUESTS = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        RequestId,
        TxnName,
        SoaComposites,
        RequestorEmail,
        CreationDate,
        DeploymentStatus,
        EnvironmentId,
        ProductCode,
        TargetWindow,
        EndDeployDate,
        DeployTypes,
        ParentRequestId;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return ust.tools
                      .bot
                      .integrator
                      .model
                      .view
                      .IntgDeploymentRequestsVORowImpl
                      .AttributesEnum
                      .firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return ust.tools
                      .bot
                      .integrator
                      .model
                      .view
                      .IntgDeploymentRequestsVORowImpl
                      .AttributesEnum
                      .firstIndex() + ust.tools
                                         .bot
                                         .integrator
                                         .model
                                         .view
                                         .IntgDeploymentRequestsVORowImpl
                                         .AttributesEnum
                                         .staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = ust.tools
                          .bot
                          .integrator
                          .model
                          .view
                          .IntgDeploymentRequestsVORowImpl
                          .AttributesEnum
                          .values();
            }
            return vals;
        }
    }


    public static final int REQUESTID = AttributesEnum.RequestId.index();
    public static final int TXNNAME = AttributesEnum.TxnName.index();
    public static final int SOACOMPOSITES = AttributesEnum.SoaComposites.index();
    public static final int REQUESTOREMAIL = AttributesEnum.RequestorEmail.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int DEPLOYMENTSTATUS = AttributesEnum.DeploymentStatus.index();
    public static final int ENVIRONMENTID = AttributesEnum.EnvironmentId.index();
    public static final int PRODUCTCODE = AttributesEnum.ProductCode.index();
    public static final int TARGETWINDOW = AttributesEnum.TargetWindow.index();
    public static final int ENDDEPLOYDATE = AttributesEnum.EndDeployDate.index();
    public static final int DEPLOYTYPES = AttributesEnum.DeployTypes.index();
    public static final int PARENTREQUESTID = AttributesEnum.ParentRequestId.index();

    /**
     * This is the default constructor (do not remove).
     */
    public IntgDeploymentRequestsVORowImpl() {
    }

    /**
     * Gets IntgDeploymentRequests entity object.
     * @return the IntgDeploymentRequests
     */
    public EntityImpl getIntgDeploymentRequests() {
        return (EntityImpl) getEntity(ENTITY_INTGDEPLOYMENTREQUESTS);
    }

    /**
     * Gets the attribute value for REQUEST_ID using the alias name RequestId.
     * @return the REQUEST_ID
     */
    public Long getRequestId() {
        return (Long) getAttributeInternal(REQUESTID);
    }

    /**
     * Sets <code>value</code> as attribute value for REQUEST_ID using the alias name RequestId.
     * @param value value to set the REQUEST_ID
     */
    public void setRequestId(Long value) {
        setAttributeInternal(REQUESTID, value);
    }

    /**
     * Gets the attribute value for TXN_NAME using the alias name TxnName.
     * @return the TXN_NAME
     */
    public String getTxnName() {
        return (String) getAttributeInternal(TXNNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for TXN_NAME using the alias name TxnName.
     * @param value value to set the TXN_NAME
     */
    public void setTxnName(String value) {
        setAttributeInternal(TXNNAME, value);
    }


    /**
     * Gets the attribute value for SOA_COMPOSITES using the alias name SoaComposites.
     * @return the SOA_COMPOSITES
     */
    public String getSoaComposites() {
        return (String) getAttributeInternal(SOACOMPOSITES);
    }

    /**
     * Sets <code>value</code> as attribute value for SOA_COMPOSITES using the alias name SoaComposites.
     * @param value value to set the SOA_COMPOSITES
     */
    public void setSoaComposites(String value) {
        setAttributeInternal(SOACOMPOSITES, value);
    }

    /**
     * Gets the attribute value for REQUESTOR_EMAIL using the alias name RequestorEmail.
     * @return the REQUESTOR_EMAIL
     */
    public String getRequestorEmail() {
        return (String) getAttributeInternal(REQUESTOREMAIL);
    }

    /**
     * Sets <code>value</code> as attribute value for REQUESTOR_EMAIL using the alias name RequestorEmail.
     * @param value value to set the REQUESTOR_EMAIL
     */
    public void setRequestorEmail(String value) {
        setAttributeInternal(REQUESTOREMAIL, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Timestamp value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for DEPLOYMENT_STATUS using the alias name DeploymentStatus.
     * @return the DEPLOYMENT_STATUS
     */
    public String getDeploymentStatus() {
        return (String) getAttributeInternal(DEPLOYMENTSTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for DEPLOYMENT_STATUS using the alias name DeploymentStatus.
     * @param value value to set the DEPLOYMENT_STATUS
     */
    public void setDeploymentStatus(String value) {
        setAttributeInternal(DEPLOYMENTSTATUS, value);
    }

    /**
     * Gets the attribute value for ENVIRONMENT_ID using the alias name EnvironmentId.
     * @return the ENVIRONMENT_ID
     */
    public Long getEnvironmentId() {
        return (Long) getAttributeInternal(ENVIRONMENTID);
    }

    /**
     * Sets <code>value</code> as attribute value for ENVIRONMENT_ID using the alias name EnvironmentId.
     * @param value value to set the ENVIRONMENT_ID
     */
    public void setEnvironmentId(Long value) {
        setAttributeInternal(ENVIRONMENTID, value);
    }

    /**
     * Gets the attribute value for PRODUCT_CODE using the alias name ProductCode.
     * @return the PRODUCT_CODE
     */
    public String getProductCode() {
        return (String) getAttributeInternal(PRODUCTCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for PRODUCT_CODE using the alias name ProductCode.
     * @param value value to set the PRODUCT_CODE
     */
    public void setProductCode(String value) {
        setAttributeInternal(PRODUCTCODE, value);
    }

    /**
     * Gets the attribute value for TARGET_WINDOW using the alias name TargetWindow.
     * @return the TARGET_WINDOW
     */
    public String getTargetWindow() {
        return (String) getAttributeInternal(TARGETWINDOW);
    }

    /**
     * Sets <code>value</code> as attribute value for TARGET_WINDOW using the alias name TargetWindow.
     * @param value value to set the TARGET_WINDOW
     */
    public void setTargetWindow(String value) {
        setAttributeInternal(TARGETWINDOW, value);
    }

    /**
     * Gets the attribute value for END_DEPLOY_DATE using the alias name EndDeployDate.
     * @return the END_DEPLOY_DATE
     */
    public Timestamp getEndDeployDate() {
        return (Timestamp) getAttributeInternal(ENDDEPLOYDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for END_DEPLOY_DATE using the alias name EndDeployDate.
     * @param value value to set the END_DEPLOY_DATE
     */
    public void setEndDeployDate(Timestamp value) {
        setAttributeInternal(ENDDEPLOYDATE, value);
    }

    /**
     * Gets the attribute value for DEPLOY_TYPE using the alias name DeployType.
     * @return the DEPLOY_TYPE
     */
    public String getDeployTypes() {
        return (String) getAttributeInternal(DEPLOYTYPES);
    }

    /**
     * Sets <code>value</code> as attribute value for DEPLOY_TYPE using the alias name DeployType.
     * @param value value to set the DEPLOY_TYPE
     */
    public void setDeployTypes(String value) {
        setAttributeInternal(DEPLOYTYPES, value);
    }

    /**
     * Gets the attribute value for PARENT_REQUEST_ID using the alias name ParentRequestId.
     * @return the PARENT_REQUEST_ID
     */
    public Long getParentRequestId() {
        return (Long) getAttributeInternal(PARENTREQUESTID);
    }

    /**
     * Sets <code>value</code> as attribute value for PARENT_REQUEST_ID using the alias name ParentRequestId.
     * @param value value to set the PARENT_REQUEST_ID
     */
    public void setParentRequestId(Long value) {
        setAttributeInternal(PARENTREQUESTID, value);
    }
}

