package ust.tools.bot.integrator.model.view;

import java.sql.Timestamp;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 06 16:54:56 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class IntgDeploymentRequestsVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public IntgDeploymentRequestsVOImpl() {
    }

    /**
     * Returns the variable value for BindTxnName.
     * @return variable value for BindTxnName
     */
    public String getBindTxnName() {
        return (String) ensureVariableManager().getVariableValue("BindTxnName");
    }

    /**
     * Sets <code>value</code> for variable BindTxnName.
     * @param value value to bind as BindTxnName
     */
    public void setBindTxnName(String value) {
        ensureVariableManager().setVariableValue("BindTxnName", value);
    }

    /**
     * Returns the variable value for BindTargetWindow.
     * @return variable value for BindTargetWindow
     */
    public String getBindTargetWindow() {
        return (String) ensureVariableManager().getVariableValue("BindTargetWindow");
    }

    /**
     * Sets <code>value</code> for variable BindTargetWindow.
     * @param value value to bind as BindTargetWindow
     */
    public void setBindTargetWindow(String value) {
        ensureVariableManager().setVariableValue("BindTargetWindow", value);
    }

    /**
     * Returns the variable value for BindRequestId.
     * @return variable value for BindRequestId
     */
    public Long getBindRequestId() {
        return (Long) ensureVariableManager().getVariableValue("BindRequestId");
    }

    /**
     * Sets <code>value</code> for variable BindRequestId.
     * @param value value to bind as BindRequestId
     */
    public void setBindRequestId(Long value) {
        ensureVariableManager().setVariableValue("BindRequestId", value);
    }

    /**
     * Returns the variable value for BindStatus.
     * @return variable value for BindStatus
     */
    public String getBindStatus() {
        return (String) ensureVariableManager().getVariableValue("BindStatus");
    }

    /**
     * Sets <code>value</code> for variable BindStatus.
     * @param value value to bind as BindStatus
     */
    public void setBindStatus(String value) {
        ensureVariableManager().setVariableValue("BindStatus", value);
    }

    /**
     * Returns the variable value for BindEnvironmentId.
     * @return variable value for BindEnvironmentId
     */
    public Long getBindEnvironmentId() {
        return (Long) ensureVariableManager().getVariableValue("BindEnvironmentId");
    }

    /**
     * Sets <code>value</code> for variable BindEnvironmentId.
     * @param value value to bind as BindEnvironmentId
     */
    public void setBindEnvironmentId(Long value) {
        ensureVariableManager().setVariableValue("BindEnvironmentId", value);
    }

    /**
     * Returns the variable value for BindCurrentDate.
     * @return variable value for BindCurrentDate
     */
    public Timestamp getBindCurrentDate() {
        return (Timestamp) ensureVariableManager().getVariableValue("BindCurrentDate");
    }

    /**
     * Sets <code>value</code> for variable BindCurrentDate.
     * @param value value to bind as BindCurrentDate
     */
    public void setBindCurrentDate(Timestamp value) {
        ensureVariableManager().setVariableValue("BindCurrentDate", value);
    }

    /**
     * Returns the variable value for BindProductCode.
     * @return variable value for BindProductCode
     */
    public String getBindProductCode() {
        return (String) ensureVariableManager().getVariableValue("BindProductCode");
    }

    /**
     * Sets <code>value</code> for variable BindProductCode.
     * @param value value to bind as BindProductCode
     */
    public void setBindProductCode(String value) {
        ensureVariableManager().setVariableValue("BindProductCode", value);
    }
}

